### ISSUE TITLE
Publig gpg key

### ISSUE THREAD

**Issue by Laffs2k5** [Azure/tflint-ruleset-azurerm-ext#6]
Hi, I would very much like to install this plugin.

Where can I find the publig GPG key to specify as `signing_key` in my `.tflint.hcl`?

Thanks

**Comment by lonegunmanb** [comment]
Hi @Laffs2k5 thanks for opening this issue, you can find a working config block [here](https://github.com/Azure/tfmod-scaffold/blob/v0.35.1/.tflint.hcl#L72-L129). Please feel free to ping me here if you have any further questions.

**Comment by Laffs2k5** [comment]
Thanks :-D
