### ISSUE TITLE
compatibility with tflint 0.48.0

### ISSUE THREAD

**Issue by matt-FFFFFF** [Azure/tflint-ruleset-azurerm-ext#7]
Hi,

I cannot run this with tflint 0.48.0. 

`Plugin "azurerm-ext" SDK version is incompatible. Compatible versions: >= 0.14.0`

Same issue with `basic-ext`

**Comment by Laffs2k5** [comment]
There is a PR to fix basic-ext: https://github.com/Azure/tflint-ruleset-basic-ext/pull/6/files
Maybe someone could bump this plugin as well?

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've upgraded the dep, now this plugin could work with tflint v0.50.1.
